[package]
name = "server"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Foundry Platform Reference Server"
repository.workspace = true

[[bin]]
name = "foundry-server"
path = "src/main.rs"

[lints]
workspace = true

[features]
default = ["postgres"]
postgres = ["foundry/postgres"]
mysql = ["foundry/mysql"]

[dependencies]
foundry = { workspace = true, default-features = false }
tokio = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
